SWE_TOPICS_EXTENDED = [
    "Internetning ishlash prinsiplari",
    "TCP/IP va protokollar",
    "DNS va domen tizimi",
    "HTTP va HTTPS protokollari",
    "CDN (Content Delivery Network)",
    "Cloud computing va serverlar geografiyasi",
    "Version control va Git workflow",
    "REST API va GraphQL",
    "Microservices arxitekturasi",
    "Monolithic arxitektura",
    "Serverless computing",
    "Load balancing va scaling",
    "Caching (Redis, Memcached)",
    "Database sharding va replication",
    "SQL va NoSQL ma’lumotlar bazalari",
    "CAP theorem",
    "Event-driven architecture",
    "Message queues (Kafka, RabbitMQ)",
    "Asynchronous programming",
    "Concurrency va parallelizm",
    "CI/CD pipeline va test automation",
    "Containerization (Docker, Kubernetes)",
    "DevOps va Infrastructure as Code",
    "TLS/SSL va ma’lumotlarni shifrlash",
    "WebSockets va real-time communication",
    "Progressive Web Apps (PWA)",
    "Responsive web design",
    "Lazy loading va optimizatsiya",
    "ETL va data pipelines",
    "Blockchain va smart contracts",
    "Feature flags va A/B testing",
    "Edge computing",
    "Rate limiting va security",
    "API throttling",
    "Health checks va monitoring",
    "Distributed systems",
    "Fault tolerance va high availability",
    "Logging va observability",
    "Versioning va backward compatibility",
    "Caching strategies (write-through, write-back)",
    "Data serialization (JSON, Protobuf, Avro)",
    "Search engine indexing va ranking algorithms",
    "Graph algorithms (BFS, DFS, Dijkstra)",
    "Sorting algorithms (QuickSort, MergeSort)",
    "Hashing va hash tables",
    "Machine learning pipeline",
    "AI inference serverlari",
    "Data visualization va dashboards",
    "ETL vs ELT farqlari",
    "Security best practices (OWASP)",
    "Authentication va Authorization (OAuth, JWT)",
    "API gateway va request routing",
    "Webhooks va event subscriptions",
    "Rate limiting va throttling",
    "Session management",
    "Cookie va localStorage ishlatilishi",
    "Cross-Origin Resource Sharing (CORS)",
    "HTTP/2 va HTTP/3 farqlari",
    "TLS handshakes va certificate verification",
    "DDoS himoya strategiyalari",
    "Zero-downtime deployments",
    "Blue-green deployments",
    "Canary releases",
    "Observability metrics va tracing",
    "Prometheus va Grafana monitoring",
    "ELK stack (Elasticsearch, Logstash, Kibana)",
    "Kafka Streams va real-time processing",
    "Message brokers va pub/sub pattern",
    "Backpressure handling",
    "Rate limiting algoritmlari",
    "Circuit breaker pattern",
    "Retry strategies va exponential backoff",
    "Load testing va stress testing",
    "Profiling va performance tuning",
    "Memory management va garbage collection",
    "Heap va stack farqlari",
    "Concurrency primitives (mutex, semaphore)",
    "Thread-safe coding practices",
    "Immutable data structures",
    "Functional programming paradigms",
    "Reactive programming (RxJS, Reactor)",
    "Actor model (Akka, Orleans)",
    "Event sourcing va CQRS",
    "State machines va workflow automation",
    "Data consistency models",
    "Strong vs eventual consistency",
    "Leader election algorithms",
    "Consensus algorithms (Raft, Paxos)",
    "Distributed locks",
    "Idempotent operations",
    "API versioning strategies",
    "Backward compatibility",
    "Feature toggles va experimentation",
    "Continuous integration best practices",
    "Continuous deployment strategies",
    "Git branching models (GitFlow, trunk-based)",
    "Code review va pull request culture",
    "Static code analysis",
    "Linting va formatting tools",
    "Unit testing va test coverage",
    "Integration testing",
    "End-to-end testing",
    "Mocking va stubbing",
    "Test-driven development (TDD)",
    "Behavior-driven development (BDD)",
    "Contract testing",
    "Dependency injection",
    "Inversion of control",
    "Service discovery",
    "API throttling va rate limiting",
    "Content negotiation (Accept headers)",
    "Serialization format comparison (JSON, XML, Protobuf)",
    "Data migration strategies",
    "Schema evolution",
    "Database indexing techniques",
    "Full-text search indexing",
    "Query optimization",
    "Connection pooling",
    "Database replication",
    "CAP theorem practical applications",
    "Consistency, Availability, Partition tolerance tradeoffs",
    "Eventual consistency in distributed databases",
    "Sharding strategies",
    "Database partitioning",
    "Caching patterns (cache aside, write-through, write-back)",
    "Reverse proxy va load balancer roles",
    "HTTP caching headers",
    "CDN edge caching",
    "TLS termination",
    "SSL offloading",
    "Micro-frontend architectures",
    "Module federation",
    "Monorepo vs polyrepo",
    "Package management (npm, pip, Maven)",
    "Dependency graph management"
    "API design best practices",
    "gRPC va RPC frameworks",
    "Server-sent events (SSE)",
    "WebRTC va real-time communication",
    "Single-page applications (SPA)",
    "Multi-page applications (MPA)",
    "Progressive enhancement",
    "Service workers va offline support",
    "Push notifications",
    "Browser storage (IndexedDB, SessionStorage)",
    "Web assembly (WASM)",
    "Edge computing security",
    "IoT protocols (MQTT, CoAP)",
    "Smart contract development",
    "Ethereum vs Solana blockchain",
    "Consensus algorithms comparison",
    "Decentralized applications (dApps)",
    "Zero-knowledge proofs",
    "Cryptography basics",
    "Asymmetric vs symmetric encryption",
    "Hash functions va digital signatures",
    "JWT token security",
    "OAuth2.0 flow",
    "OpenID Connect",
    "Authentication vs Authorization",
    "Role-based access control (RBAC)",
    "Attribute-based access control (ABAC)",
    "Session hijacking prevention",
    "CSRF va XSS protection",
    "Secure coding guidelines",
    "Input validation va sanitization",
    "SQL injection prevention",
    "NoSQL injection prevention",
    "Secure password storage (bcrypt, scrypt, Argon2)",
    "API rate limiting",
    "Bot detection strategies",
    "CAPTCHA implementation",
    "Content Security Policy (CSP)",
    "CORS policy best practices",
    "TLS/SSL certificate management",
    "HSTS implementation",
    "HTTP security headers",
    "Security logging va monitoring",
    "Intrusion detection systems",
    "Penetration testing basics",
    "Threat modeling",
    "CI/CD security",
    "Secrets management (Vault, AWS Secrets Manager)",
    "Infrastructure as Code security",
    "Container security (Docker, Podman)",
    "Kubernetes security best practices",
    "Network segmentation",
    "Firewall configuration",
    "Zero-trust network",
    "Data loss prevention",
    "Backup and disaster recovery",
    "High availability design",
    "Multi-region deployment",
    "Failover strategies",
    "Chaos engineering",
    "Observability pillars (logs, metrics, traces)",
    "OpenTelemetry integration",
    "Monitoring alerting best practices",
    "SLAs, SLOs, SLIs",
    "Application profiling tools",
    "Memory leak detection",
    "CPU profiling",
    "Thread contention issues",
    "Garbage collection tuning",
    "Immutable infrastructure",
    "Blue/green deployments",
    "Canary releases",
    "Feature flagging strategies",
    "A/B testing in production",
    "Synthetic monitoring",
    "Real user monitoring (RUM)",
    "Load testing tools (JMeter, Locust)",
    "Stress testing vs soak testing",
    "Chaos monkey experiments",
    "Service mesh (Istio, Linkerd)",
    "API gateway patterns",
    "Request routing strategies",
    "Traffic shaping",
    "Circuit breaker pattern",
    "Retry with exponential backoff",
    "Bulkhead isolation",
    "Message queue patterns",
    "Pub/sub systems",
    "Event sourcing",
    "CQRS architecture",
    "Saga pattern",
    "Data pipelines orchestration",
    "ETL vs ELT",
    "Data lake vs data warehouse",
    "Data catalog and lineage",
    "Streaming data processing",
    "Batch vs stream processing",
    "Kafka vs RabbitMQ comparison",
    "Message deduplication",
    "Event replay",
    "Stateful vs stateless services",
    "Functional programming in distributed systems",
    "Reactive programming",
    "Backpressure handling",
    "Idempotency in APIs",
    "Timeout and retry strategies",
    "Feature toggles",
    "Code freeze strategies",
    "Release train methodology",
    "Monorepo vs multi-repo",
    "Package versioning (SemVer)",
    "Dependency management",
    "Transitive dependency vulnerabilities",
    "Static site generators",
    "Server-side rendering (SSR)",
    "Jamstack architecture",
    "GraphQL schema design",
    "GraphQL query optimization",
    "Pagination strategies",
    "Error handling in APIs",
    "Observability in microservices",
    "Distributed tracing",
    "Correlation IDs in logs",
    "Logging standards",
    "Structured logging",
    "JSON logging",
    "Binary logging formats",
    "Message compression techniques",
    "Content negotiation",
    "API evolution and deprecation",
    "Backward compatibility strategies",
    "Forward compatibility strategies",
    "Data serialization formats (Protobuf, Avro, Thrift)",
    "Schema evolution in Protobuf"
]
