SWE_TOPICS_EXTENDED = [
    "Internet qanday ishlaydi?",
    "Brauzerda Enter bosganingizda nimalar sodir bo‘ladi?",
    "DNS nima va domen nomi qanday topiladi?",
    "HTTP va HTTPS farqi nimada?",
    "Frontend va Backend o‘rtasidagi farq",
    "API nima va u qanday ishlaydi?",
    "REST API nima degani?",
    "GraphQL nima va REST bilan farqi?",
    "Cloud computing oddiy tilda",
    "Server nima va u qaerda joylashgan?",
    "IP manzil va port nima?",
    "TCP/IP nima uchun kerak?",
    "Ping nima qiladi?",
    "Server bilan mijoz qanday bog‘lanadi?",
    "Cookie va localStorage farqi nimada?",
    "Session nima va qanday ishlaydi?",
    "CORS nima va nega xatolik beradi?",
    "Load balancing oddiy tilda",
    "Cache nima va saytni qanday tezlashtiradi?",
    "CDN nima va saytni tezlashtiradimi?",
    "Domen qanday ishlaydi?",
    "DNS caching nima?",
    "Firewall nima qiladi?",
    "Proxy server nima va nima uchun kerak?",
    "VPN qanday ishlaydi?",
    "Ping va latency farqi",
    "Client-server modeli nima?",
    "Static va dynamic saytlar farqi",
    "HTTP so‘rov turlari (GET, POST, PUT, DELETE)",
    "JSON nima va nima uchun ishlatiladi?",
    "XML o‘rnini nima bosdi?",
    "API key nima va uni qanday himoyalash kerak?",
    "IP v4 va v6 farqi nimada?",
    "Hosting nima va saytni qaerda saqlanadi?",
    "SSL sertifikat nima qiladi?",
    "TLS nima va HTTPS bilan bog‘liqligi",
    "Browser cache nima qiladi?",
    "User agent nima degani?",
    "HTTP status kodlar (200, 404, 500) nima anglatadi?",
    "301 va 302 redirect farqi",
    "Domain vs Subdomain farqi",
    "DNS propagation nima?",
    "DNS record turlari (A, CNAME, MX)",
    "Server uptime nima degani?",
    "Reverse proxy nima?",
    "API gateway nima qiladi?",
    "Webhook nima degani?",
    "Request va Response qanday ishlaydi?",
    "Payload nima degani?",
    "Server loglari nimani anglatadi?",
    "Frontend dasturchi nimalar qiladi?",
    "Backend dasturchi nimalar qiladi?",
    "Fullstack dasturchi kim?",
    "HTML nima va nima uchun kerak?",
    "CSS nima va veb sahifani qanday bezaydi?",
    "JavaScript nima va nima uchun muhim?",
    "DOM nima degani?",
    "React nima va nima uchun mashhur?",
    "Vue.js nima?",
    "Angular nima?",
    "Framework va kutubxona farqi nimada?",
    "SPA (Single Page Application) nima degani?",
    "MPA (Multi Page Application) nima?",
    "Component nima va nima uchun kerak?",
    "State management nima degani?",
    "Virtual DOM nima qiladi?",
    "Responsive design nima?",
    "Adaptive design bilan farqi nimada?",
    "Bootstrap nima?",
    "Tailwind CSS nima va nimasi bilan qulay?",
    "CSS preprocessor nima (SASS, LESS)?",
    "JavaScript vs TypeScript farqi",
    "NPM va Node.js nima?",
    "Backend tili sifatida Python haqida",
    "Django framework nima?",
    "Flask nima va qachon ishlatiladi?",
    "Express.js nima?",
    "FastAPI nima?",
    "REST API backendda qanday yaratiladi?",
    "Database bilan backend qanday bog‘lanadi?",
    "ORM nima degani?",
    "SQL nima va ma’lumotlar bazasi bilan ishlash qanday?",
    "NoSQL nima va qachon ishlatiladi?",
    "PostgreSQL vs MySQL farqi",
    "MongoDB nima va qanday ishlaydi?",
    "Redis nima va cache sifatida qanday ishlatiladi?",
    "Backendda autentifikatsiya qanday ishlaydi?",
    "Token nima va JWT qanday ishlaydi?",
    "OAuth nima degani?",
    "Session authentication nima?",
    "API rate limiting nima?",
    "Logging nima va nega kerak?",
    "Error handling qanday amalga oshiriladi?",
    "Middleware nima degani?",
    "Backend arxitekturasi qanday bo‘ladi?",
    "Load balancer backendda nima qiladi?",
    "Serverdan clientga javob qanday qaytadi?",
    "Backendda fayl yuklash qanday ishlaydi?",
    "CORS muammosi backendda qanday hal qilinadi?",
    "API testing qanday o‘tkaziladi?",
    "Postman nima uchun ishlatiladi?",
    "Ma’lumotlar bazasi nima va nima uchun kerak?",
    "SQL nima degani?",
    "SQL va NoSQL farqi nimada?",
    "Table, row, column nima degani?",
    "Primary key va foreign key nima?",
    "Query nima va qanday ishlaydi?",
    "Database indexing nima va nima uchun kerak?",
    "Database normalization oddiy tilda",
    "JOIN nima va qanday ishlaydi?",
    "LEFT JOIN va INNER JOIN farqi",
    "View nima va nima uchun ishlatiladi?",
    "Transaction nima degani?",
    "ACID nima degani?",
    "Database backup nima uchun kerak?",
    "Replication nima va nima uchun ishlatiladi?",
    "Sharding nima degani?",
    "Data migration nima degani?",
    "ORM nima va qanday foyda beradi?",
    "Connection pooling nima?",
    "Database performance optimization haqida",
    "SQL injection nima va undan qanday himoyalanish kerak?",
    "NoSQL nima uchun paydo bo‘lgan?",
    "MongoDB nima degani?",
    "Redis qanday ishlaydi?",
    "Caching nima va database bilan aloqasi qanday?",
    "Database trigger nima?",
    "Stored procedure nima?",
    "Materialized view nima?",
    "Data consistency nima degani?",
    "Eventual consistency nima degani?",
    "CAP theorem oddiy tilda",
    "Database scaling qanday amalga oshiriladi?",
    "Read replica nima?",
    "Write-ahead log nima?",
    "Backup va restore jarayoni qanday?",
    "Data loss prevention nima?",
    "ETL nima degani?",
    "ETL va ELT farqi nimada?",
    "Data pipeline nima?",
    "Data lake va data warehouse farqi",
    "Big Data nima degani?",
    "Data analytics oddiy tilda",
    "Data visualization nima va nima uchun kerak?",
    "Dashboard nima va qanday yaratiladi?",
    "SQL’da GROUP BY qanday ishlaydi?",
    "Aggregation nima degani?",
    "Database monitoring nima uchun kerak?",
    "Query optimization texnikalari",
    "Database locking nima?",
    "Transaction isolation level nima degani?",
    "Deadlock nima va undan qanday qochiladi?",
    "Dasturchi bo‘lish uchun matematikani bilish shartmi?",
    "Junior dasturchi uchun eng katta xatolar",
    "Yangi dasturchilar ko‘p qiladigan 5 ta xato",
    "Kod yozishda motivatsiyani qanday saqlash mumkin?",
    "Burnout nima va undan qanday saqlanish kerak?",
    "Bug degani nima va dasturchilar uni qanday topadi?",
    "Debug qilish san’ati — sabrning haqiqiy sinovi",
    "Dasturchilar uchun yaxshi uxlash nega muhim?",
    "Pomodoro texnikasi nima va qanday ishlaydi?",
    "Kod yozayotganda fokusni qanday saqlash kerak?",
    "Dasturchi uchun eng foydali odatlar",
    "Teamwork nima va nega muhim?",
    "Code review jarayoni qanday bo‘ladi?",
    "Yaxshi commit message qanday yoziladi?",
    "Dasturchi sifatida stressni boshqarish usullari",
    "Intervyuda ko‘p beriladigan savollar",
    "Portfolio nima va uni qanday tuzish kerak?",
    "GitHub profilingizni qanday chiroyli qilish mumkin?",
    "Open source loyihalarda qatnashish foydasi",
    "Pair programming nima degani?",
    "Mentor bilan ishlashning foydalari",
    "Dasturchi sifatida tanqidni qanday qabul qilish kerak?",
    "Tech interviewda qo‘rquvni yengish usullari",
    "Dasturchi sifatida samarali gapirishni o‘rganish",
    "Remote ishlashning afzalliklari va kamchiliklari",
    "Freelance dasturchilik haqida bilish kerak bo‘lgan narsalar",
    "Startupda ishlash va katta kompaniyada ishlash farqi",
    "Dasturchilar uchun eng foydali kitoblar",
    "Junior, Middle va Senior darajalari orasidagi farq",
    "Soft skills nima va dasturchi uchun qanchalik muhim?",
    "Tog‘ri so‘rov berish san’ati (Googling skills)",
    "Dasturchilar uchun vaqtni boshqarish usullari",
    "Productivity app’lar dasturchilar uchun",
    "Yomon kod va yaxshi kod farqi nimada?",
    "Clean Code degani nima?",
    "Dasturchi uchun toza ish muhiti nega muhim?",
    "Code smell nima degani?",
    "Code refactoring nima va qachon kerak bo‘ladi?",
    "Technical debt nima degani?",
    "Dasturchi uchun klaviatura shortcutilarining foydasi",
    "Dasturchilar nega ko‘p kafe ichishadi?",
    "Kodni boshqalarga tushunarli yozish san’ati",
    "Teamda kommunikatsiya madaniyati",
    "Bug topgan paytdagi his-tuyg‘ular 😅",
    "Deadline bosimi bilan qanday kurashish kerak?",
    "Tech sohasida ingliz tili qanchalik muhim?",
    "Yangi texnologiyalarni o‘rganishda yo‘qolib ketmaslik siri",
    "Code va hayot o‘rtasidagi o‘xshashliklar",
    "Dasturchi uchun motivatsion filmlar va seriallar",
    "Har kuni kod yozish foydali odatmi?",
    "DevOps nima va nima uchun kerak?",
    "Cloud computing oddiy tilda tushuntirish",
    "AWS, Azure va Google Cloud farqi nimada?",
    "Docker nima va nima uchun ishlatiladi?",
    "Container nima degani?",
    "Kubernetes nima degani?",
    "Virtual machine va container farqi",
    "CI/CD nima degani?",
    "Continuous integration nima uchun kerak?",
    "Continuous deployment qanday ishlaydi?",
    "Pipeline nima degani?",
    "Infrastructure as Code nima degani?",
    "Terraform nima va qanday ishlaydi?",
    "Ansible nima va nimaga kerak?",
    "Monitoring nima va nega muhim?",
    "Prometheus nima degani?",
    "Grafana nima uchun ishlatiladi?",
    "ELK Stack nima degani?",
    "Log nima va uni nima uchun saqlaymiz?",
    "Server uptime degani nima?",
    "Load balancer nima va qanday ishlaydi?",
    "Reverse proxy nima degani?",
    "Nginx nima va qayerda ishlatiladi?",
    "Apache server haqida qisqacha",
    "Caching server nima?",
    "DNS server qanday ishlaydi?",
    "CDN nima degani va qanday foyda beradi?",
    "Scaling nima va qachon kerak bo‘ladi?",
    "Horizontal scaling va vertical scaling farqi",
    "Serverless nima degani?",
    "Lambda function nima degani?",
    "Blue-green deployment nima degani?",
    "Canary deployment nima?",
    "Zero downtime deployment nima degani?",
    "Rollback nima degani?",
    "Failover nima va qanday ishlaydi?",
    "Backup nima va uni qanday qilish kerak?",
    "Disaster recovery nima degani?",
    "High availability nima uchun muhim?",
    "Cluster nima degani?",
    "Microservices nima degani?",
    "Monolithic arxitektura nima degani?",
    "Microservices va Monolith farqi",
    "Service discovery nima degani?",
    "API gateway nima vazifani bajaradi?",
    "Load testing nima degani?",
    "Stress testing nima degani?",
    "Server monitoring qanday amalga oshiriladi?",
    "Uptime monitoring nima?",
    "DevOps va dasturchi o‘rtasidagi farq",
    "Continuous improvement madaniyati nima?",
    "Dasturiy ta’minot xavfsizligi nima degani?",
    "Cybersecurity nima va nega har kim uchun muhim?",
    "Ma’lumotlarni shifrlash (encryption) nima degani?",
    "SSL va TLS nima farq qiladi?",
    "HTTPS nima uchun xavfsiz hisoblanadi?",
    "Firewall nima va qanday himoya qiladi?",
    "Antivirus qanday ishlaydi?",
    "Phishing nima va undan qanday saqlanish kerak?",
    "2FA (ikki bosqichli autentifikatsiya) nima degani?",
    "Password manager nima uchun kerak?",
    "Hash nima va u qanday ishlaydi?",
    "JWT token nima degani?",
    "OAuth nima degani?",
    "Session nima va qanday boshqariladi?",
    "Cookie nima va nima uchun kerak?",
    "CSRF hujumi nima degani?",
    "XSS hujumi nima degani?",
    "SQL injection nima degani?",
    "Data breach nima degani?",
    "Zero trust security nima degani?",
    "Bug bounty nima degani?",
    "Penetration testing nima degani?",
    "Ethical hacking nima degani?",
    "OWASP nima va nima uchun muhim?",
    "Security patch nima degani?",
    "API security nima uchun muhim?",
    "Network security nima degani?",
    "VPN qanday ishlaydi?",
    "Proxy server nima vazifani bajaradi?",
    "Privacy va anonymity farqi",
    "Social engineering nima degani?",
    "Backup va recovery strategiyasi nima?",
    "Testing nima va nima uchun kerak?",
    "Unit test nima degani?",
    "Integration test nima degani?",
    "E2E (end-to-end) test nima degani?",
    "Test coverage nima degani?",
    "TDD (Test Driven Development) nima degani?",
    "BDD (Behavior Driven Development) nima degani?",
    "Mocking nima degani?",
    "Automation testing nima uchun kerak?",
    "Manual testing va automation farqi",
    "Bug nima degani?",
    "Regression testing nima degani?",
    "Performance testing nima degani?",
    "QA engineer nima ish qiladi?",
    "AI nima degani va qanday ishlaydi?",
    "Machine learning nima degani?",
    "Deep learning nima degani?",
    "Neural network nima degani?",
    "ChatGPT qanday ishlaydi?",
    "Natural Language Processing (NLP) nima degani?",
    "Computer vision nima degani?",
    "Recommendation system nima degani?",
    "AI modeli qanday o‘qitiladi?",
    "Dataset nima degani?",
    "Bias (og‘ish) nima degani AI’da?",
    "Overfitting nima degani?",
    "Underfitting nima degani?",
    "AI etikasi nima degani?",
    "Prompt engineering nima degani?",
    "AI bilan ishlaydigan dasturchining roli qanday?",
    "Future of AI — kelajakda bizni nima kutyapti?",
    "AI dasturchilarni almashtiradimi?",
    "AI orqali ishlashni o‘rganish yo‘llari",
    "AI va inson birga ishlaganda nimalar bo‘ladi?",
    "AI xavflari va afzalliklari",
    "Quantum computing nima degani?",
    "Blockchain nima degani oddiy tilda?",
    "NFT nima va qanday ishlaydi?",
    "Web3 nima degani?",
    "Metaverse nima degani?",
    "IoT (Internet of Things) nima degani?",
    "Smart devices qanday ishlaydi?",
    "AR va VR texnologiyalari farqi",
    "3D printing qanday ishlaydi?",
    "Voice assistantlar qanday ishlaydi?",
    "AI va tibbiyot sohasidagi yangiliklar",
    "AI va ta’lim sohasida qo‘llanishi",
    "Cybersecurity va AI bog‘liqligi",
    "AI model xavfsizligi nima degani?",
    "Deepfake nima va qanday aniqlanadi?",
    "AI bilan ishlaydigan botlar qanday yaratiladi?",
    "Chatbot nima va qanday ishlaydi?",
    "AI coding assistantlar qanday ishlaydi?",
    "AI yordamida rasm chizish texnologiyalari",
    "AI va audio tahlil texnologiyalari",
    "Data science nima degani?",
    "Data engineer va data scientist farqi",
    "Model deployment nima degani?",
    "MLOps nima degani?",
    "AI monitoring va observability nima?",
    "AI kelajagi haqida qiziqarli faktlar",
    "AI bilan ishlashda insonning roli qanday o‘zgaradi?"
]
